# Generated by Django 4.0.1 on 2022-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_telesettings_tg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telesettings',
            name='tg_coming_date',
            field=models.DateField(auto_now=True, max_length=200, verbose_name='Дата приезда'),
        ),
    ]
