# Generated by Django 4.0.1 on 2022-01-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_comentcrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True, verbose_name='Дата приезда'),
        ),
    ]
