# Generated by Django 4.0.1 on 2022-01-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='coming_date',
        ),
    ]
