# Generated by Django 4.0.1 on 2022-02-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_order_date_order_coming_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coming_date',
            field=models.DateField(verbose_name='Дата приезда'),
        ),
    ]
